### ISSUE TITLE
Problem with synced_timers

### ISSUE THREAD

**Issue by bbkiwi** [AEFeinstein/Super-2021-Swadge-FW-Sandbox#2]
**Behavior**
Under certain circumstances, `syncedTimersCheck` will raise excepton 28.

**Steps To Reproduce**
`syncedTimerDisarm` a `syncedTimer_t` in its own call back routine.
This removes it from the linked list and 'confuses' `syncedTimersCheck`.

**Where I ran into the problem**
Line 325 p2pConnection.c but I'm suspect line 819, 821, 187 and 260 could cause problems too.
Line 308 hpatimer.c and line 337 user_main.c need looking at too.

**Other potential similar problems**
I haven't tested but  `syncedTimerArm` will also cause
problems, since it starts by calling `syncedTimerDisarm`. (But even if it didn't
it would change the linked list which might confuse `syncedTimersCheck`.) 
I haven't looked where `syncedTimerArm` has been used. 

**Question**
Why do you call `syncedTimerDisarm` at the beginning of `syncedTimerArm`, but not
in `syncedTimerSetFn`? Comments at line 43, 44 and 70, 71 may need to be changed.
With `syncedTimerDisarm` at the beginning of `syncedTimerArm`, it looks like lines 89 to 98 can go.

**Comment by AEFeinstein** [comment]
Hm, modifying a linked list mid-iteration is indeed bad. I can clean that up.

The comments at line 43, 44 and 70, 71 come from the [API reference](https://www.espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf)'s notes on calling `os_timer_setfn()` and `os_timer_arm()` respectively. I can clean up the `syncedTimer_t` comments because it's allowed there.

**Comment by bbkiwi** [comment]
For the OLED fix I'd feel more comfortable with `    if(1000 <= framesDrawn)` on line 280 in user_main.c. 

I've merged your fixes into my stuff (which can switched between a few modes) and I'm testing now (mode_test) and so far no glitch. BUT as I write (after 15 mins) **BUGGGGGG!!!**
Will try using your master just to make sure it not related to anything I've done. **BUG** here too after 10 mins.

Running my ring test mode which started resetting when I brought in syncedTimers.
The exception is no longer raised when I used your synced_timers fix. However I'm still worried that using a copy of the linked list in `syncedTimersCheck` might still cause unintended behavior. If a synced_timer's callback disarms other timers later in the list, Those timer's callback will be executed when they should not be. 

General question about `os_timer_t` but applies to `syncedTimer_t` The manual says minimum interval is 5 ms. So what about code line 233 in hpatimer.c and lines 205 and 870 p2pConnection.c?

I thought I read somewhere (but can't find it again by googling) that there is a limit of 7 software timers for ESP8266. Is there or am I dreaming?

**Comment by AEFeinstein** [comment]
> For the OLED fix I'd feel more comfortable with if(1000 <= framesDrawn) on line 280 in user_main.c.

OK, changed

> I've merged your fixes into my stuff (which can switched between a few modes) and I'm testing now (mode_test) and so far no glitch. BUT as I write (after 15 mins) **BUGGGGGG!!!**

I tried two more things, One brings down the SPI speed to under 800KHz (the OLED is rated at that, we were running slightly faster). The other is to rewrite the OLED parameters when the screen is redrawn. I've had a display running fine for many minutes, but that isn't a guarantee of a fix.

> If a synced_timer's callback disarms other timers later in the list, Those timer's callback will be executed when they should not be.

This was also fixed by tracking `isArmed`. I thought about timers more in general, and thought it would be cleaner and safer to iterate through and call the callbacks, then cleanup the linked list, so I did that too.

> General question about os_timer_t but applies to syncedTimer_t The manual says minimum interval is 5 ms. So what about code line 233 in hpatimer.c and lines 205 and 870 p2pConnection.c?

Experimentally, I've found that intervals less than 5ms still work as expected. Because they're software timers, the intervals less than 5ms may be more erratic.

> I thought I read somewhere (but can't find it again by googling) that there is a limit of 7 software timers for ESP8266. Is there or am I dreaming?

I think you're dreaming. I don't remember any timer limit, nor can I find one in the API reference.

**Comment by bbkiwi** [comment]
Will test today. Cesar is a bit worse and Im worried.

**Comment by bbkiwi** [comment]
**OLED Glitch still there**
merged f2f30f814dc0889c (run below 800Hz) into my stuff, mode_user went haywire in under 2.5 hrs
also merged d36cf02bc821d94e (reset OLED) and bug still there.

**syncedTimer failing now**
Animation in mode_test still works, but mag pets no longer connect, and my ring stuff  scroll text has stopped working, connection using a modified p2pConnection now fails.

**Comment by AEFeinstein** [comment]
> OLED Glitch still there

I'm out of ideas, but at least it's happening less frequently now? Maybe you could try bumping `OLED_FREQ` all the way down from 800 to 400?

> syncedTimer failing now

There were two bugs. magpet is back to working with them fixed.
* eba3967f7a87b679ef612fdef4b9fd42c4702c64
* b61e27b98f9fee5357ef3cf44c05177c46663dba

Sending my best wishes to Cesar!

**Comment by bbkiwi** [comment]
Those two commits above fixed the failure to connect and scrolling in my stuff, but there are still problems. Have a look at 
https://github.com/bbkiwi/Super-2021-Swadge-FW-Sandbox/tree/bugexample

**Comment by AEFeinstein** [comment]
@bbkiwi your new issue has nothing to do with timers or the OLED. It's just inefficiently trying to draw a lot of chars which are off the screen. A more optimized `plotChar()` is below which scrolls smoothly. Please double check if your issue is actually a timer issue before posting to this ticket.

```
int16_t ICACHE_FLASH_ATTR plotChar(int16_t x, int16_t y,
                                   char character, const sprite_t* table, color col)
{
    if(character >= ' ')
    {
        // Make everything uppercase
        if ('a' <= character && character <= 'z')
        {
            character = (char) (character - 'a' + 'A');
        }

        // Only attempt to plot the character if it may be in bounds
        // The max size of a radiostars char is 12x12
        if(x >= OLED_WIDTH || x <= -12 || y >= OLED_HEIGHT || y <= -12)
        {
            return x + table[character - ' '].width + 1;
        }

        // Plot the sprite
        return plotSprite(x, y, &table[character - ' '], col);
    }
    return x;
}
```

**Comment by bbkiwi** [comment]
I realise this is an artificial example however the slowing down and eventual dying did not occur if sync timers are replaced with os_timers. So I assume it had something to do with the sync timers.

**Comment by bbkiwi** [comment]
Did you see my last comment? Also joust using os_timers had a much longer text message scrolled in the same way which produced no problem.

**Comment by AEFeinstein** [comment]
The fairer test would be to replace the `synced_timer` in your test code with an `os_timer` and see if it speeds up significantly.

The motivation for this change is that `os_timer` callback functions must execute quickly, similar to interrupts. When they don't, the firmware crashes. We saw this happen with the snortmelon animation where scrolling and redrawing took too long. In contrast, `synced_timers` simply raises a flag in the `os_timer` callback, which is very fast, then executes the callback in `procTask()`, which is registered with `system_os_task()`, and allows for much longer functions to run. Charles pointed out that attribute of `procTask()` to me late last year.

So `synced_timers` may simply run slowly when `os_timers` would crash. If it's causing some separate slowdown, I can look into that eventually.

**Comment by bbkiwi** [comment]
Hi Adam, I had done the fairer test you suggested. That is what https://github.com/AEFeinstein/Super-2021-Swadge-FW-Sandbox/issues/2#issuecomment-613043992 was about. 

I'll document the results better.

https://github.com/bbkiwi/Super-2021-Swadge-FW-Sandbox/tree/74fea3fb3dcf4cdeaaa5e3d6829c654b03521a4a
os_timers in both user_main and a modified test mode which scrolls a very long message in the inefficient way. It is very jerky from the start, but does not crash (at least for the 10 mins I had it running). 

For a previous commit on that branch https://github.com/bbkiwi/Super-2021-Swadge-FW-Sandbox/commits/314c1a18e5fb0d6d578b89b8414e7f5a00b81a65 sync timers are used. It starts with fast scrolling but immediately goes slower and jerky. It slows more and more after after about 3 minutes dies. 

At the top of branch syncbug
https://github.com/bbkiwi/Super-2021-Swadge-FW-Sandbox/commits/syncbug
the accelerator callback is set to NULL as well. No glitchy behavour at all (still all os_timers used)

If set allerator callback to NULL in 314c1a18e5f (using syhcTimers), the movement is glitchy but does not slow down or die.

**Comment by AEFeinstein** [comment]
I replaced every `syncedTimer_t` with `os_timer_t` in `bugexample` and it was still jerky. I agree that `os_timer_t` was a bit smoother than `syncedTimer_t`, though I still believe `syncedTimer_t` is less prone to crashes. In both cases the timer was running too long. I'd be more curious if you can find a situation where an `os_timer_t` is smooth but a `syncedTimer_t` isn't.

**Comment by AEFeinstein** [comment]
Timers have been good for a while, so closing this ticket.
